name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select Terraform Action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

      confirm:
        description: 'Proceed with action?'
        required: true
        type: boolean
        default: false

jobs:
  terraform-apply:
    if: github.event.inputs.action == 'apply'
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.3

      - name: Terraform Init
        run: ./scripts/init.sh

      - name: Terraform Plan
        run: ./scripts/plan.sh

      - name: Terraform Apply
        if: github.event.inputs.confirm == true
        run: ./scripts/apply.sh

      - name: Action Skipped
        if: github.event.inputs.confirm == false
        run: echo "You selected 'false', so Terraform Apply was skipped. Only the plan was generated."

  terraform-destroy:
    if: github.event.inputs.action == 'destroy'
    name: Terraform Destroy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.3

      - name: Terraform Init
        run: ./scripts/init.sh

      - name: Terraform Destroy
        if: github.event.inputs.confirm == true
        run: ./scripts/destroy.sh

      - name: Destroy Skipped
        if: github.event.inputs.confirm == false
        run: echo "You selected 'false', so the destroy action was skipped."