name: Terraform CI/CD anish

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select Terraform Action'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy

      confirm:
        description: 'Proceed with action?'
        required: true
        default: 'no'
        type: choice
        options:
          - yes
          - no

jobs:
  apply-full:
    if: github.event.inputs.action == 'apply' && github.event.inputs.confirm == 'yes'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.3

      - name: Terraform Init
        run: ./scripts/init.sh

      - name: Terraform Plan
        run: ./scripts/plan.sh

      - name: Terraform Apply
        run: ./scripts/apply.sh

  apply-preview:
    if: github.event.inputs.action == 'apply' && github.event.inputs.confirm == 'no'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.3

      - name: Terraform Init (Preview)
        run: ./scripts/init.sh

      - name: Terraform Plan (Preview)
        run: ./scripts/plan.sh

  destroy:
    if: github.event.inputs.action == 'destroy' && github.event.inputs.confirm == 'yes'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.3

      - name: Terraform Destroy
        run: ./scripts/destroy.sh

  skip:
    if: github.event.inputs.action == 'destroy' && github.event.inputs.confirm == 'no'
    runs-on: ubuntu-latest
    steps:
      - name: Skip Destroy
        run: echo "You selected 'destroy' but confirmation was 'no'. Skipping."
